# Coding Attention Mechanism

### Simple attention mechanism

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import torch

In [3]:
inputs = torch.tensor(
    [
        [0.43, 0.15, 0.89], ## your
        [0.55, 0.87, 0.66], # journey
        [0.57, 0.85, 0.64], # starts
        [0.22, 0.58, 0.33], # with
        [0.77, 0.25, 0.10], # one
        [0.05, 0.80, 0.55] # steps
    ]
)

In [4]:
input_query = inputs[1]
input_query

tensor([0.5500, 0.8700, 0.6600])

In [5]:
input_1 = inputs[0]
input_1

tensor([0.4300, 0.1500, 0.8900])

In [6]:
torch.dot(input_query, input_1)

tensor(0.9544)

In [7]:
for i in range(len(inputs)):
    res = torch.dot(inputs[i], input_query)
    print(res)

tensor(0.9544)
tensor(1.4950)
tensor(1.4754)
tensor(0.8434)
tensor(0.7070)
tensor(1.0865)


In [10]:
query = inputs[1]

attn_score = torch.empty(inputs.shape[0])

for i, i_x in enumerate(inputs):
    attn_score[i] = torch.dot(i_x, query)

attn_score = torch.softmax(attn_score, dim=0)
attn_score

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])

In [11]:
query = inputs[1]

context_vec = torch.zeros(query.shape)

for i, i_x in enumerate(inputs):
    context_vec += attn_score[i] * i_x
print(context_vec)

tensor([0.4419, 0.6515, 0.5683])
